### ISSUE TITLE
Add `replace` post processor mechanism for fields

### ISSUE THREAD

**Issue by witjem** [witjem/feedpls#10]
**Context**
Some news website add some prefix `- DNN News` to title, like: `Apple presented a new iPhone - DNN News`

**Proposal**
Add `replace` postprocesor which will be replace content by `regex`. 

```yaml
- id: some-blog-open-source
  title: The Some Blog | Open Source
  description: Open Source Archives
  url: https://someblog.blog/category/open-source/
  matchers:
    itemUrl:
      selector: article a
      attr: href
    title:
      selector: title
    description:
      selector: meta[name='description']
      attr: content
    published:
      selector: meta[name='parsely-pub-date']
      attr: content
      layout: 2006-01-02T15:04:05Z07:00
 
  postprocessors:  // new field on yaml
    - replace:
        field: title // can be: title, description
        from: some_regex
        to: ""
``` 

_You can always offer your option_
