### ISSUE TITLE
Support author for items

### ISSUE THREAD

**Issue by witjem** [witjem/feedpls#15]
**Context**
RSS and Atom items has author field. It will be good if service will be support it.

**Proposal**
Add optional field `author` to feeds.yml config
```yaml
matchers:
  engine: xpath
  author: # Optional props.
    name:
      expr: //meta[@name='author']/@content
    email:
      expr: //meta[@name='author']/@content
```

Should ignore author on the RSS if author name not found.

**Reminder**
Updates docs and examples too.
