### ISSUE TITLE
Added support parsing data from yoast

### ISSUE THREAD

**Issue by witjem** [witjem/feedpls#6]
**Context**
Some website use [yoast](https://yoast.com) for SEO. This plugin on the HTML page has all needed information for feed.

```xml
<script type="application/ld+json" class="yoast-schema-graph">yoast json</script>
```

**Proposal**
Maybe do feed config like this?
```yaml
- id: feed-id
  title: feed title
  description: feed desc
  url: http://example.com/news
  matchers:
    engine: xpath-yoast
    itemUrl:
      expr: //article//a/@href
```
